eureka:
  instance:
    hostname: 52.66.178.202
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://52.66.178.202:8761/eureka/
cors:
  set:
    allowed:
      origins: http://localhost:5173/,
               http://localhost:3000/,
               http://localhost:4200/,
               http://localhost:8989/
api:
  redirect:
    uris: 
       http://localhost:3000/oauth2/redirect,
       http://localhost:5173/oauth2/redirect
user:
  service:
    api:
      host: http://USER-SERVICE/users
      url:
        demo: ${user.service.api.host}/api/v1/user-to-admin/demo
        getall: ${user.service.api.host}/api/v1/user-to-admin/get/allUsers
        getbyid: ${user.service.api.host}/api/v1/user-to-admin/getbyid/
        update_nonlocked: ${user.service.api.host}/api/v1/user-to-admin/update/nonlocked/byid/
        users_by_ids: ${user.service.api.host}/api/v1/user-to-therapist/users-byids
therapist:
  service:
    api:
      host: http://THERAPIST-SERVICE/therapists
      url:
        getall: ${therapist.service.api.host}/api/v1/public/get/allTherapists
        getbyid: ${therapist.service.api.host}/api/v1/therapist-to-admin/getbyid/
        activate: ${therapist.service.api.host}/api/v1/therapist-to-admin/activate/byid/
        enabled: ${therapist.service.api.host}/api/v1/therapist-to-admin/enabled/byid/
        update_categories: ${therapist.service.api.host}/api/v1/therapist-to-admin/update-categories/byid/
        all-reviews: ${therapist.service.api.host}/api/v1/public-to-admin/all-reviews
        count-reviews: ${therapist.service.api.host}/api/v1/public-to-admin/count-reviews
        byid-review: ${therapist.service.api.host}/api/v1/public-to-admin/byid-review/
        all-bookings: ${therapist.service.api.host}/api/v1/public-to-admin/all-bookings
        count-bookings: ${therapist.service.api.host}/api/v1/public-to-admin/count-bookings
        byid-booking: ${therapist.service.api.host}/api/v1/public-to-admin/byid-booking/
        all-payments: ${therapist.service.api.host}/api/v1/public-to-admin/all-payments
        count-payments: ${therapist.service.api.host}/api/v1/public-to-admin/count-payments
        byid-payment: ${therapist.service.api.host}/api/v1/public-to-admin/byid-payment/
        booking: ${therapist.service.api.host}/api/v1/therapist-to-user/book
        reschedule: ${therapist.service.api.host}/api/v1/therapist-to-user/book-reschedule/byid/
        update_payment: ${therapist.service.api.host}/api/v1/therapist-to-user/
        booking-byid: ${therapist.service.api.host}/api/v1/therapist-to-user/booking-byid/
        bookings-byuser: ${therapist.service.api.host}/api/v1/therapist-to-user/booking-byuserid/
        cancel_booking: ${therapist.service.api.host}/api/v1/therapist-to-user/cancel/
        therapists_byuserid: ${therapist.service.api.host}/api/v1/therapist-to-user/book-therapists/by-user/
category:
  service:
    api:
      host: http://THERAPIST-SERVICE/therapists
      url:
        add: ${category.service.api.host}/api/v1/therapist-to-admin/category/add
        delete: ${category.service.api.host}/api/v1/therapist-to-admin/category/delete/
        update: ${category.service.api.host}/api/v1/therapist-to-admin/category/update/
review:
  service:
    api:
      host: http://THERAPIST-SERVICE/therapists
      url:
       create: ${review.service.api.host}/api/v1/reviews/create
       update_review: ${review.service.api.host}/api/v1/reviews/update/
       delete_review: ${review.service.api.host}/api/v1/reviews/delete/
       by_user: ${review.service.api.host}/api/v1/reviews/user/
       by_therapist: ${review.service.api.host}/api/v1/reviews/therapist/
       by_user_therapist: ${review.service.api.host}/api/v1/reviews
       by_booking: ${review.service.api.host}/api/v1/reviews/booking/
chat:
  service:
    api:
      host: http://THERAPIST-SERVICE/therapists
      url:
       create: ${chat.service.api.host}/api/v1/messages-to-user/create
       chat_byroomid: ${chat.service.api.host}/api/v1/messages-to-user/by-roomId/
       therapistsinfo_byuserid: ${chat.service.api.host}/api/v1/messages-to-user/therapists/
